language: go

go:
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.10.x"
  - master

before_install:
  - wget "https://github.com/Masterminds/glide/releases/download/v0.13.2/glide-v0.13.2-linux-amd64.tar.gz"
  - mkdir -p $HOME/bin
  - tar -vxz -C $HOME/bin --strip=1 -f glide-v0.13.2-linux-amd64.tar.gz
  - export PATH="$HOME/bin:$PATH"
  - go get golang.org/x/lint/golint

script:
  - make ci